default: &default
  adapter: postgresql
  encoding: unicode
  pool: 10

development:
  <<: *default
  database: kyklo_dev
  host: localhost

test:
  <<: *default
  host: localhost
  database: kyklo_test

production:
  <<: *default
  database: kyklo_prod
